### ISSUE TITLE
Navigation bar 

### ISSUE THREAD

**Issue by ronadarabi** [cse110-sp24-group6/cse110-sp24-group6#34]
The vertical navigation bar on the homepage looks good, but the bar should extend all the way to the bottom of the page, including the footer area. This should be replicated on all other pages. For desktop, the bar should be vertical as in the picture (taken from the homepage). Mobile view will be horizontal (also pictured, taken from the daily log page). Make sure that all the icons match (use the icons on the homepage), and that the design schemes are consistent (for example, the color of the daily log icon in the vertical bar picture is different than the other icons). 
![verticalnavbar](https://github.com/cse110-sp24-group6/cse110-sp24-group6/assets/68180000/bf5cc0c6-4712-4c2b-81d4-e371755f216f)
![horizontalnavbar](https://github.com/cse110-sp24-group6/cse110-sp24-group6/assets/68180000/6c8ea801-6434-463f-b534-11981a2c1477)

**Comment by Vasilistaxo** [comment]
I could work on the navbar setting for all the pages and add the horizontal ones to all of them properly for the mobile small screens if you could assign this task to me. Thank you!
